language: node_js
node_js:
- '7'
sudo: false
before_script:
- psql -c 'create database nofloassemblydb;' -U postgres
script: npm test
env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost/nofloassemblydb
services:
  - postgresql
